import type { Kurs, Sitat, Samarbeidspartner } from './types';

export const mockKurs: Kurs[] = [
  {
    id: '1',
    slug: 'norsk-a1-nybegynner',
    tittel: 'Norsk A1 – Nybegynner',
    ingress: 'Lær grunnleggende norsk fra bunnen av. Kurset er tilpasset voksne uten forkunnskaper.',
    beskrivelseLang: 'Dette kurset passer for deg som aldri har lært norsk før. Vi går gjennom grunnleggende grammatikk, dagligdagse fraser og enkel konversasjon. Kurset er finansiert av IMDI og er gratis for deg som deltaker.',
    hvaLaererDu: ['Grunnleggende ordforråd', 'Enkel setningsoppbygging', 'Dagligdagse fraser', 'Lese og skrive enkle tekster'],
    hvemPasser: 'Nyankomne til Norge som ønsker å lære norsk fra grunnen av.',
    coverbilde: null,
    kurstype: 'norsk',
    cefrNivaa: 'A1',
    forsidePrioritet: 1,
    prisOere: 0,
    gratis: true,
    finansiering: 'imdi',
    klasser: [
      {
        id: 'k1',
        startDato: '2026-09-01',
        sluttDato: '2027-02-28',
        sted: 'Kristiansand',
        type: 'fysisk',
        maksPlasser: 20,
        ledigePlasser: 8,
      },
    ],
    laereplan: [
      { tittel: 'Modul 1: Hei og ha det', beskrivelse: 'Hilsener og enkle presentasjoner' },
      { tittel: 'Modul 2: Familie og venner', beskrivelse: 'Ord for familiemedlemmer og relasjoner' },
      { tittel: 'Modul 3: Mat og drikke', beskrivelse: 'Bestille mat og handle' },
    ],
  },
  {
    id: '2',
    slug: 'norsk-b1-mellomtrinn',
    tittel: 'Norsk B1 – Mellomtrinn',
    ingress: 'Ta norskferdighetene dine til neste nivå med fokus på muntlig kommunikasjon og skriftlig fremstilling.',
    beskrivelseLang: 'For deg som allerede kan grunnleggende norsk og ønsker å forbedre deg. Kurset er nettbasert og fleksibelt, tilpasset deg med jobb eller familie.',
    hvaLaererDu: ['Avansert grammatikk', 'Akademisk skriving', 'Muntlig presentasjon', 'Norsk på arbeidsplassen'],
    hvemPasser: 'Deg som behersker A2-nivå og ønsker å nå B1.',
    coverbilde: null,
    kurstype: 'norsk',
    cefrNivaa: 'B1',
    forsidePrioritet: 2,
    prisOere: 350000,
    gratis: false,
    finansiering: 'ingen',
    klasser: [
      {
        id: 'k2',
        startDato: '2026-08-15',
        sluttDato: '2026-12-15',
        type: 'nettbasert',
        maksPlasser: 25,
        ledigePlasser: 12,
      },
    ],
    laereplan: [
      { tittel: 'Modul 1: Kommunikasjon i arbeidslivet', beskrivelse: 'Formelle og uformelle samtaler' },
      { tittel: 'Modul 2: Medier og samfunn', beskrivelse: 'Lese og diskutere nyheter' },
      { tittel: 'Modul 3: Norsk kultur og identitet', beskrivelse: 'Dypere forståelse av norsk samfunn' },
    ],
  },
  {
    id: '3',
    slug: 'fagbrev-bua',
    tittel: 'Fagbrev i barne- og ungdomsarbeid (BUA)',
    ingress: 'Formell kompetanse som barne- og ungdomsarbeider – finansiert av HK Dir.',
    beskrivelseLang: 'Utdanningen kvalifiserer deg til å jobbe profesjonelt med barn og unge i barnehage, SFO og fritidsklubber. Hele opplæringen er finansiert av HK Dir.',
    hvaLaererDu: ['Pedagogisk arbeid med barn', 'Barns utvikling og lek', 'Sikkerhet og førstehjelp', 'Samarbeid med foresatte'],
    hvemPasser: 'Deg som jobber eller ønsker å jobbe med barn og unge.',
    coverbilde: null,
    kurstype: 'fagbrev',
    cefrNivaa: 'ingen',
    forsidePrioritet: 3,
    prisOere: 0,
    gratis: true,
    finansiering: 'hkdir',
    klasser: [
      {
        id: 'k3',
        startDato: '2026-10-01',
        sluttDato: '2027-06-01',
        sted: 'Kristiansand',
        type: 'hybrid',
        maksPlasser: 15,
        ledigePlasser: 5,
      },
    ],
    laereplan: [
      { tittel: 'Del 1: Grunnleggende pedagogikk', beskrivelse: 'Teorier om barns utvikling' },
      { tittel: 'Del 2: Praktisk arbeid', beskrivelse: 'Praksis i barnehage eller SFO' },
      { tittel: 'Del 3: Fagprøve', beskrivelse: 'Forberedelse og gjennomføring av fagprøve' },
    ],
  },
  {
    id: '4',
    slug: 'norsk-for-arbeidslivet',
    tittel: 'Norsk for arbeidslivet',
    ingress: 'Styrk norskferdighetene dine i en jobbkontekst – for deg på B1-nivå.',
    beskrivelseLang: 'Kurset fokuserer på norsk du faktisk bruker på jobb: møter, e-poster, telefonsamtaler og faglig kommunikasjon. Hybrid undervisning – noen samlinger fysisk, resten nettbasert.',
    hvaLaererDu: ['Profesjonell e-postskriving', 'Møteledelse og deltakelse', 'Fagterminologi', 'Presentasjonsteknikk'],
    hvemPasser: 'Innvandrere i arbeidslivet som vil styrke sin norsk.',
    coverbilde: null,
    kurstype: 'arbeidsliv',
    cefrNivaa: 'B1',
    forsidePrioritet: 4,
    prisOere: 250000,
    gratis: false,
    finansiering: 'ingen',
    klasser: [
      {
        id: 'k4',
        startDato: '2026-09-01',
        sluttDato: '2026-12-01',
        sted: 'Kristiansand / Nett',
        type: 'hybrid',
        maksPlasser: 20,
        ledigePlasser: 0,
      },
    ],
    laereplan: [
      { tittel: 'Modul 1: Jobbsøking og intervju', beskrivelse: 'Skriv CV og forbered deg til intervju' },
      { tittel: 'Modul 2: På arbeidsplassen', beskrivelse: 'Kommunikasjon med kolleger og ledere' },
      { tittel: 'Modul 3: Skriftlig kommunikasjon', beskrivelse: 'E-post, rapporter og referat' },
    ],
  },
  {
    id: '5',
    slug: 'livsmestring',
    tittel: 'Livsmestring',
    ingress: 'Kurs i psykisk helse, stressmestring og personlig utvikling for voksne.',
    beskrivelseLang: 'Et praktisk kurs som gir deg verktøy til å håndtere hverdagens utfordringer. Vi dekker stressmestring, søvn, relasjoner og personlig vekst.',
    hvaLaererDu: ['Stressmestring', 'Mindfulness og avslapning', 'Bedre søvnvaner', 'Kommunikasjon i relasjoner'],
    hvemPasser: 'Alle voksne som ønsker å styrke sin psykiske helse og livskvalitet.',
    coverbilde: null,
    kurstype: 'livsmestring',
    cefrNivaa: 'ingen',
    forsidePrioritet: 5,
    prisOere: 150000,
    gratis: false,
    finansiering: 'ingen',
    klasser: [
      {
        id: 'k5',
        startDato: '2026-09-15',
        sluttDato: '2026-11-15',
        sted: 'Stavanger',
        type: 'fysisk',
        maksPlasser: 18,
        ledigePlasser: 10,
      },
    ],
    laereplan: [
      { tittel: 'Uke 1–2: Kjenn deg selv', beskrivelse: 'Identifiser stressfaktorer og ressurser' },
      { tittel: 'Uke 3–4: Verktøy for mestring', beskrivelse: 'Praktiske teknikker og øvelser' },
      { tittel: 'Uke 5–8: Vedlikehold og vekst', beskrivelse: 'Bygge gode vaner over tid' },
    ],
  },
];

export const mockSitater: Sitat[] = [
  {
    id: '1',
    deltagerNavn: 'Amina Hassan',
    kursNavn: 'Norsk A1 – Nybegynner',
    sitatTekst: 'Etter kurset kunne jeg endelig snakke med naboene mine. Lærerne var tålmodige og kurset var gratis. Anbefaler det til alle!',
  },
  {
    id: '2',
    deltagerNavn: 'Reza Ahmadi',
    kursNavn: 'Fagbrev i barne- og ungdomsarbeid',
    sitatTekst: 'Jeg jobbet i barnehage uten fagbrev i fem år. Nå har jeg papirene på det jeg kan, og fikk lønnsøkning. Takk til Aftenskolen!',
  },
  {
    id: '3',
    deltagerNavn: 'Maria Kowalski',
    kursNavn: 'Norsk for arbeidslivet',
    sitatTekst: 'Kurset hjalp meg å bli tryggere i møter og skrive bedre e-poster. Sjefen min la merke til fremgangen min.',
  },
];

export const mockSamarbeidspartnere: Samarbeidspartner[] = [
  { id: '1', navn: 'IMDI', beskrivelse: 'Integrerings- og mangfoldsdirektoratet finansierer norskopplæring for nyankomne.', lenke: 'https://www.imdi.no', kategori: 'finansiering' },
  { id: '2', navn: 'Akademisk Studieforbund', beskrivelse: 'AKS er vårt studieforbund og sikrer kvaliteten i all opplæring.', lenke: 'https://www.aks.no', kategori: 'studieforbund' },
  { id: '3', navn: 'Nordplus', beskrivelse: 'Nordplus støtter nordisk utdanningssamarbeid.', lenke: 'https://www.nordplusonline.org', kategori: 'internasjonalt' },
  { id: '4', navn: 'HK Dir', beskrivelse: 'Direktoratet for høyere utdanning og kompetanse finansierer fagbrevopplæring.', lenke: 'https://hkdir.no', kategori: 'finansiering' },
  { id: '5', navn: 'Kompetanseforbundet', beskrivelse: 'Kompetanseforbundet arbeider for økt satsing på voksenopplæring.', kategori: 'bransje' },
  { id: '6', navn: 'Aktivitetssenter for Nervøse', beskrivelse: 'Lokalt aktivitetssenter i Kristiansand – samarbeider om livsmestrings­kurs.', kategori: 'lokal' },
];
